# Generated by Django 3.2 on 2022-02-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
