# Generated by Django 3.2 on 2022-02-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('update_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
